### ISSUE TITLE
Web klasöründe görünüm sorunu

### ISSUE THREAD

**Issue by emre-koc** [halilselcuk/Arduino-Gunes-Enerjisi-Kontrol-Sistemi#1]
index ve giris html dosyalarını açtım ancak stylelar yüklenmiyor gibi görünüyor. index.htm dosyasının üst altnda head kısımları yok. bu bir template dosyası mı? başka dosya olmadığı için de yorum yapamadım fazla.

**Comment by halilselcuk** [comment]
Web klasöründeki index.htm ve giris.htm şablon dosyalarıdır. SD klasöründeki INDEX dosyası tarafından sayfaya dahil edilirler.

**Comment by emre-koc** [comment]
O dosyanın adını index.html gibi değiştirebilirsen localde test ederken kolaylık sağlar.

**Comment by halilselcuk** [comment]
Teşekkürler. Bu şekilde güncelledim.
