### ISSUE TITLE
Uzaktan çekilen dosyalar

### ISSUE THREAD

**Issue by emre-koc** [halilselcuk/Arduino-Gunes-Enerjisi-Kontrol-Sistemi#2]
Uzaktan çekilen css ve js dosyalarını cihazın üzerine yüklerseniz daha stabil bir ortam oluşacaktır. Uzakta bulunan dosyalar silinip değiştirildiği taktirde arayüz çalışma hale gelir.

**Comment by halilselcuk** [comment]
CSS ve JS dosyalarını Arduino üzerinden almak sayfaları yavaşlatacaktır. Uzaktaki dosyalar release'de belirlenen sürüm numarasına göre alınır. Dosyalarda silme, güncelleme gerektiğinde yeni bir sürüm oluşturulmalı ve eski sürümdeki dosyalara dokunulmamalıdır.
Güncel dosyalar kullanılmak istendiğinde ise sd/index.html dosyasındaki sürüm numaraları güncellenmelidir.
